stages:
  - deploy

variables:
  PROJECT_DIR: "/home/kdt/1liceworks-ai"

before_script:
  - echo "Deploying Flask App..."
  - cd $PROJECT_DIR
  - git config --global --add safe.directory $PROJECT_DIR/1liceworks-ai
  - sudo chown -R gitlab-runner:gitlab-runner $PROJECT_DIR/1liceworks-ai
  - cd 1liceworks-ai/
  - git config --global credential.helper store
  - echo "https://$GITLAB_USERNAME:$GITLAB_PASSWORD@kdt-gitlab.elice.io" > ~/.git-credentials
  - git checkout main
  - git pull origin main
  - cd ..
  - source venv/bin/activate
  - cd 1liceworks-ai/

deploy:
  stage: deploy
  tags:
    - all
  script:
    - export GEMINI_API_KEY=$GEMINI_API_KEY
    - pip install -r requirements.txt
    - pkill -f gunicorn || true
    - cd $PROJECT_DIR/1liceworks-ai/1liceworks-ai
    - gunicorn -w 4 -b 0.0.0.0:5000 app:app --daemon
  only:
    - main
